Repository Spikeysanju/MotionToast, pull requests merged in 2020-11, with the labels that each got.

#19 Add Custom Toast Title
  motiontoast/src/main/java/www/sanju/motiontoast/MotionToast.kt
Labels: enhancement

#23 Fix Bug & Refactor Code
  .github/workflows/android_ci.yml
  app/build.gradle
  app/src/androidTest/java/www/sanju/motiontoastapp/ExampleInstrumentedTest.kt
  app/src/main/AndroidManifest.xml
  app/src/main/java/www/sanju/motiontoastapp/MainActivity.kt
  app/src/main/res/layout/full_color_toast.xml
  app/src/main/res/layout/motion_toast.xml
  app/src/test/java/www/sanju/motiontoastapp/ExampleUnitTest.kt
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
  motiontoast/build.gradle
  motiontoast/src/main/java/www/sanju/motiontoast/MotionToast.kt
  motiontoast/src/main/res/font/montserrat_bold.xml
  motiontoast/src/main/res/font/montserrat_regular.xml
  motiontoast/src/main/res/layout/full_color_toast.xml
  motiontoast/src/main/res/layout/motion_toast.xml
  motiontoast/src/main/res/values/dimen.xml
  motiontoast/src/main/res/values/font_certs.xml
  motiontoast/src/main/res/values/preloaded_fonts.xml
  motiontoast/src/main/res/values/strings.xml
Labels: Improvement, bug

#24 Fix new android and refactor
  .gitignore
  .idea/codeStyles/Project.xml
  .idea/gradle.xml
  motiontoast/src/main/java/www/sanju/motiontoast/MotionToast.kt
Labels: Improvement
